insight:
  image: metabase/metabase
  container_name: insight
  volumes:
    - /home/ubuntu/data/metabase:/metabase-data
  restart: always
  ports:
    - 3001:3000
  environment:
    - MB_DB_FILE=/metabase-data/metabase.db
  links:
    - insight-db:db
insight-db:
  image: mysql:5.6
  container_name: insight-db
  ports:
    - 3307:3306
  volumes:
    - /home/ubuntu/data/insight:/var/lib/mysql
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD={{MYSQL_ROOT_PASSWORD}}
    - MYSQL_DATABASE=atlas